### ISSUE TITLE
Suggest for manga poster

### ISSUE THREAD

**Issue by Cologler** [SyncYomi/SyncYomi#11]
I suggest syncing the manga poster content (or only the URL) to the SyncYomi server and showing it on the web panel.

**Comment by KaiserBh** [comment]
Hi, may I know why you want the manga poster on the web panel? Currently, it syncs everything from tachiyomi, so if you need the poster url, it should be in the database as well?

**Comment by Cologler** [comment]
The poster can make the record look good 😄
