### ISSUE TITLE
Suggestion: unRAID Community Application

### ISSUE THREAD

**Issue by LarveyOfficial** [SyncYomi/SyncYomi#12]
I personally use unRAID for my server hosting, and I think it would be amazing if this project would be added to the community applications for unRAID, allowing users to easily and quickly startup an instance of SyncYomi.

Here is a link explaining how to add an application to the community applications (At least from what I could find googling, I personally haven't done this myself)
https://forums.unraid.net/topic/57181-docker-faq/#comment-566084

Please let me know if you need any help or any kind of testing.

**Comment by KaiserBh** [comment]
> I personally use unRAID for my server hosting, and I think it would be amazing if this project would be added to the community applications for unRAID, allowing users to easily and quickly startup an instance of SyncYomi.
> 
> Here is a link explaining how to add an application to the community applications (At least from what I could find googling, I personally haven't done this myself) https://forums.unraid.net/topic/57181-docker-faq/#comment-566084
> 
> Please let me know if you need any help or any kind of testing.

Heya, Sorry I been busy but I will look into that in the upcoming days.

**Comment by xiaodoudou** [comment]
@LarveyOfficial you can do that via the plugin docker compose manager, you create a stack "syncyomi" and you edit it with this:

`version: '3.9'
services:
  syncyomi:
    image: ghcr.io/syncyomi/syncyomi:latest
    restart: unless-stopped
    container_name: syncyomi
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /mnt/user/config/syncyomi/config:/config
    ports:
      - '8282:8282'
    networks:
      frontend:
        ipv4_address: 172.30.20.227
      backend:

  postgres:
    container_name: syncyomi-postgres
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=SyncYomi
      - POSTGRES_PASSWORD=SyncYomi
    ports:
      - '5434:5432'
    volumes:
      - /mnt/user/config/syncyomi/postgres:/var/lib/postgresql/data
    networks:
      backend:

volumes:
  postgres:
    driver: local

networks:
    backend:
        name: syncyomi_backend
        external: false
    frontend:
        name: br0
        external: true`

Feel free to change the configuration to your ease.
Cheers,

**Comment by xiaodoudou** [comment]
If you don't wan't to use Docker Compose plugin, you can inject your own template.

Here the template content:
```
<?xml version="1.0"?>
<Container version="2">
  <Name>SyncYomi</Name>
  <Repository>ghcr.io/syncyomi/syncyomi:latest</Repository>
  <Registry/>
  <Network>bridge</Network>
  <MyIP/>
  <Shell>sh</Shell>
  <Privileged>false</Privileged>
  <Support/>
  <Project/>
  <Overview>SyncYomi is an open-source project designed to offer a seamless synchronization experience for your Tachiyomi manga reading progress and library across multiple devices. This server can be self-hosted, allowing you to sync your Tachiyomi library effortlessly.&#xD;
More info at: https://github.com/SyncYomi/SyncYomi</Overview>
  <Category/>
  <WebUI>http://[IP]:[PORT:8282]/</WebUI>
  <TemplateURL/>
  <Icon>https://github.com/SyncYomi/SyncYomi/blob/develop/.github/images/logo.png</Icon>
  <ExtraParams/>
  <PostArgs/>
  <CPUset/>
  <DateInstalled>1699880475</DateInstalled>
  <DonateText/>
  <DonateLink/>
  <Requires/>
  <Config Name="Config Path" Target="/config" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/config/syncyomi2/</Config>
  <Config Name="Port" Target="8282" Default="8282" Mode="tcp" Description="" Type="Port" Display="always" Required="false" Mask="false">8282</Config>
</Container>

```

You can put the file at `/boot/config/plugins/dockerMan/templates-user` as `my-SyncYomi.xml`

Then via the `Docker` tab on `Unraid`, you click `Add Container` and you select `SyncYomi`

It is a work arround while while the app is not published.

**Comment by xiaodoudou** [comment]
@KaiserBh I have submit the XML to Unraid and waiting their approval so people using Unraid can directy install it via the AppStore.

I will let you know when it is published.

Cheers,

**Comment by KaiserBh** [comment]
> @KaiserBh I have submit the XML to Unraid and waiting their approval so people using Unraid can directy install it via the AppStore.
> 
> I will let you know when it is published.
> 
> Cheers,

Thanks, I appreciate that!

**Comment by KaiserBh** [comment]
@LarveyOfficial Thanks to @xiaodoudou  It seem like it's added now. https://unraid.net/community/apps?q=SyncYomi

Closing.
