### ISSUE TITLE
[Feature] Provide API Endpoint for last time Sync

### ISSUE THREAD

**Issue by baal000** [SyncYomi/SyncYomi#20]
The idea is to provide an api endpoint from which you can get the time of the last sync so the clients can check that before downloading the whole database to decide if a sync is necessary (at least for the automated sync).

This would also need a change in the client so the Client checks if its last time changed is the same as the last synced of the server.
This would reduce network load which might be a good idea for mobile devices

**Comment by xiaodoudou** [comment]
On the principle I will agree with the idea approach to reduce the sync payload/data exchange via a Mobile network.
I would suggest to produce a hash of the database instead of a sync time as source of truth.

**Comment by KaiserBh** [comment]
> The idea is to provide an api endpoint from which you can get the time of the last sync so the clients can check that before downloading the whole database to decide if a sync is necessary (at least for the automated sync).
> 
> This would also need a change in the client so the Client checks if its last time changed is the same as the last synced of the server.
> This would reduce network load which might be a good idea for mobile devices

The latest version has an api endpoint for sync lock files that have last_sync.

https://github.com/SyncYomi/SyncYomi/commit/e18dea8c960fe1bbb15a473cc08df273525cab1c

I have yet implemented to thr the client side, currently only using it to prevent race conditions, and can also update the data from the client side, basically feature already exist just need to be implemented, that being said I will probably implement it in near future once it's merged by tachiyomi side.

**Comment by xiaodoudou** [comment]
Good job!
Ping me when you need me to run some test to it 👍
