### ISSUE TITLE
Cant sync manga. "Could not get manga data for api key

### ISSUE THREAD

**Issue by nosut** [syncyomi/syncyomi#42]
Running in docker. Syncyomi starts and I can make an account and sign in. After creating API key and putting it in the SY app and hitting sync now this is the docker log:

`ERR could not get manga data for api key: 537dfgdfg3d42fdgdfg546dfgdfg0e5f67b | module=mdata stack=[{"func":"MangaRepo.GetMangaDataByApiKey","line":"166","source":"mdata.go"},{"func":"service.GetMangaDataByApiKey","line":"71","source":"service.go"},{"func":"service.GetSyncData","line":"117","source":"service.go"},{"func":"syncHandler.getSyncData","line":"179","source":"sync.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).routeHTTP","line":"444","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"73","source":"mux.go"},{"func":"(*Mux).Mount.func1","line":"316","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"Server.IsAuthenticated.func1","line":"38","source":"middleware.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*ChainHandler).ServeHTTP","line":"31","source":"chain.go"},{"func":"(*Mux).routeHTTP","line":"444","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"73","source":"mux.go"},{"func":"(*Mux).Mount.func1","line":"316","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).routeHTTP","line":"444","source":"mux.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Cors).Handler.func1","line":"236","source":"cors.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"LoggerMiddleware.func1.1","line":"84","source":"middleware.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"Recoverer.func1","line":"43","source":"recoverer.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"RealIP.func1","line":"36","source":"realip.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"RequestID.func1","line":"76","source":"request_id.go"},{"func":"HandlerFunc.ServeHTTP","line":"2122","source":"server.go"},{"func":"(*Mux).ServeHTTP","line":"90","source":"mux.go"}] error=error executing query: sql: no rows in result set `

**Comment by kaiserbh** [comment]
Are you using the latest version? `v.1.0.0`? and make sure you are on the latest build on TachiyomiSY.
