### ISSUE TITLE
Allow closing webui

### ISSUE THREAD

**Issue by huajideshutiao** [syncyomi/syncyomi#53]
The current webui is only used to configure SyncYomi's key, and although it can be avoided by adjusting the baseURL, it is still somewhat unsettling. I hope to add a configuration item in the configuration file that allows not using webui.

**Comment by kaiserbh** [comment]
Not planned, sorry, the plan was adding other stuff like logging etc to the webui as well but I just got busy and never ended up shipping it, the PR is still open for it #30
