### ISSUE TITLE
issue starting docker

### ISSUE THREAD

**Issue by iguanatamer** [syncyomi/syncyomi#54]
Hi,

I've run into this issue trying to after starting the docker image. It loops this error indefinitely.

```Attaching to syncyomi
syncyomi  | 2024/08/29 23:54:18 error creating file: "open /config/config.toml: permission denied"
syncyomi  | 2024/08/29 23:54:18 write error: "open /config/config.toml: permission denied"
syncyomi  | 2024/08/29 23:54:18 config read error: "open /config/config.toml: no such file or directory"
syncyomi  | {"level":"fatal","module":"database","stack":[{"func":"(*DB).openSQLite","line":"31","source":"sqlite.go"},{"func":"(*DB).Open","line":"66","source":"database.go"},{"func":"main","line":"58","source":"main.go"},{"func":"main","line":"250","source":"proc.go"},{"func":"goexit","line":"1598","source":"asm_amd64.s"}],"error":"enable wal: unable to open database file: out of memory (14)","time":"2024-08-29T23:54:18Z","message":"could not open sqlite db connection"}
syncyomi exited with code 1
```

this is my config: 

```version: "3.9"

services:
  syncyomi:
    container_name: syncyomi
    image: ghcr.io/syncyomi/syncyomi:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    user: 1000:1000
    volumes:
      - /root/dockers/syncyomi/config:/config
    ports:
      - 8282:8282
```

**Comment by imagochan** [comment]
I have the same issue, I havent been able to run syncyomi on google cloud compute engine free tier on a e2-micro vm instance due to this using the docker compose steps too.

**Comment by kaiserbh** [comment]
> Hi,
> 
> I've run into this issue trying to after starting the docker image. It loops this error indefinitely.
> 
> ```Attaching to syncyomi
> syncyomi  | 2024/08/29 23:54:18 error creating file: "open /config/config.toml: permission denied"
> syncyomi  | 2024/08/29 23:54:18 write error: "open /config/config.toml: permission denied"
> syncyomi  | 2024/08/29 23:54:18 config read error: "open /config/config.toml: no such file or directory"
> syncyomi  | {"level":"fatal","module":"database","stack":[{"func":"(*DB).openSQLite","line":"31","source":"sqlite.go"},{"func":"(*DB).Open","line":"66","source":"database.go"},{"func":"main","line":"58","source":"main.go"},{"func":"main","line":"250","source":"proc.go"},{"func":"goexit","line":"1598","source":"asm_amd64.s"}],"error":"enable wal: unable to open database file: out of memory (14)","time":"2024-08-29T23:54:18Z","message":"could not open sqlite db connection"}
> syncyomi exited with code 1
> ```
> 
> this is my config: 
> 
> ```version: "3.9"
> 
> services:
>   syncyomi:
>     container_name: syncyomi
>     image: ghcr.io/syncyomi/syncyomi:latest
>     restart: unless-stopped
>     environment:
>       - TZ=${TZ}
>     user: 1000:1000
>     volumes:
>       - /root/dockers/syncyomi/config:/config
>     ports:
>       - 8282:8282
> ```


Try using minimal docker-compose config.

```docker
version: "3.9"

services:
  syncyomi:
    container_name: syncyomi
    image: ghcr.io/syncyomi/syncyomi:latest
    restart: unless-stopped
    ports:
      - 8282:8282
```

**Comment by gdm257** [comment]
It seems host user `1000` has not permission to read/write `/root/dockers/syncyomi/config`. To grant permissions, run:

`sudo chmod -R 777 /root/dockers/syncyomi/config`
or
`sudo chown -R 1000:1000 /root/dockers/syncyomi/config; sudo chmod -R 770 /root/dockers/syncyomi/config`

**Comment by Siarune** [comment]
I deploy mine on Coolify, and removing the user line entirely fixes the issue for me.
