### ISSUE TITLE
[Question] Possible to sync page read?

### ISSUE THREAD

**Issue by kanjieater** [SyncYomi/SyncYomi#9]
I saw the PR in progross & wanted to say thanks for the work on adding this integration for TachiYomi. I've been hoping for a while to have a solution that allows for syncing between devices. I was unclear if this also would support syncing the exact page read between devices? 

I had a [request ](https://github.com/tachiyomiorg/tachiyomi/issues/5978) open for this for a while, and was wondering if the new feature you are proposing in https://github.com/tachiyomiorg/tachiyomi/pull/9326 would accomplish this as well?

In all transparency, I use Komga as my server for most of my tachiyomi content and would hope to accomplish something similar to SyncYomi via Komga, that way I can read comics and sync them on my desktop as well.

**Comment by KaiserBh** [comment]
> I saw the PR in progross & wanted to say thanks for the work on adding this integration for TachiYomi. I've been hoping for a while to have a solution that allows for syncing between devices. I was unclear if this also would support syncing the exact page read between devices? 
> 
> I had a [request ](https://github.com/tachiyomiorg/tachiyomi/issues/5978) open for this for a while, and was wondering if the new feature you are proposing in https://github.com/tachiyomiorg/tachiyomi/pull/9326 would accomplish this as well?
> 
> In all transparency, I use Komga as my server for most of my tachiyomi content and would hope to accomplish something similar to SyncYomi via Komga, that way I can read comics and sync them on my desktop as well.

Hey there! I'm glad you're excited about the Tachiyomi integration PR. As for your question about syncing the exact page read between devices, yes, the proposed feature should be able to handle that too! It supports syncing read status, unread status, libraries, and categories - essentially everything the backup feature offers.

If you want to know more or need help setting it up, feel free to join Discord and catch me there.

[Discord](https://discord.gg/xbUEemPz)
